name: Deploy to Github-Pages

on:
  push:
    branches: ["develop"]
    paths: ["docs/**"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: mdBook Action
        uses: peaceiris/actions-mdbook@v2
        
      - run: mdbook build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book

