name: Build and Publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io/Mobility-Data-Space/mds-logging-house-client

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Publish
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: -Pversion=${{ env.IMAGE_TAG }} publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ github.token }}
