name: Build and Publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io/truzzt/mds-ap3
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_TAG: ${{ github.event.release.name }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Publish
        uses: gradle/gradle-build-action@v3
        with:
          arguments: -Pversion=${{ env.IMAGE_TAG }} publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ github.token }}
